<?php include "include/head.php"?>
<!DOCTYPE html>

<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    
<head>
        <title>Home | The Plannets Association</title>
        <?php include "include/header.php"; ?>
        <style type="text/css">
        	p{
        		margin: 0;
        	}
        </style>
        
</head>
    <body>
	
	
		<?php include "include/nav.php"?>

		
	New Change

		<div class="container">
			
			<div class="top-content">
				<div class="row">
					<div class="col-md-12">
			            <div class="u-cause-wrapper">
			                <span class="u-cause-title">
			                	<a href="#" class="close-u-cause">
			                		<i class="fa fa-times"></i>
			                	</a>
			                	Announcements
			                </span>
			                <div class="u-cause clearfix">                        
			                    <dl class="inner-carousel clearfix">
			                    	
			                        <dd><marquee WIDTH=1000 onmouseover="this.stop();" onmouseout="this.start();"><?=htmlspecialchars_decode(anything('dsc','description',1));?></marquee></dd>
			                        
			                        
			                        
			                        
			                    </dl> <!-- /.inner-carousel -->
			                </div> <!-- /.u-cause -->
			            </div> <!-- /.u-cause-wrapper -->
					</div> <!-- /.col-md-12 -->
				</div> <!-- /.row -->

				<div class="slider-wrapper">
					<div class="row">
						<div class="col-md-4">
							 <?php 
            if(isset($_POST['submit'])){
                check_all_var(); 
                //generate query from post
                $query='';
                foreach($_POST as $key=>$value) if($key != "submit") $query .="`$key`='$value',";
                $query = substr($query, 0, -1);
                
                if(mysqli_query($link,"INSERT INTO `".$prefix."membership` SET ".$query)){
                    $to = $_POST['email'];
                     $to1 = $site->site_owner_email;
                    $subject = "Membership Form";
                    
                    
                    $headers = 'From: noreply@shopping365.in' . "\r\n";
                    $headers.= 'MIME-Version: 1.0' . "\r\n";
                    $headers.= 'Content-type: text/html;charset=UTF-8' . "\r\n";
                    $message="Contact Enquiry Received with below details,<br> ";
                    $message.="Subject: ".$_POST['subject']."<br>";
                    $message.="Name: ".$_POST['name']."<br>";
                    $message.="Email: ".$_POST['email']."<br>";
                     $message.="Phone: ".$_POST['phone']."<br>";
                       $message.="This is an autogenerated email, please do not reply to this email.";
                    mail($to, $subject, $message, $headers);
                     mail($to1, $subject, $message, $headers);
                //insert all text info

                    echo '<p class="alert alert-success"><i class="fa fa-check fa-fw"></i>  Thank you. We will get back to you soon.</p>';
                  }
                else { 
                    
                    echo '<p class="alert alert-danger"><i class="fa fa-warning fa-fw"></i> Sorry! There is an error while adding details!</p>';   
                  }

            }
        ?>
							<div class="subscribe-form">
								<h3 class="widget-title">Honourable Membership</h3>
								
								<form method="post" enctype="multipart/form-data">
								    <fieldset>
										<label for="name">Name:</label>
										<input type="text"  name="name" class="form-control">
								    </fieldset>
								    <fieldset>
										<label for="last-name">Address:</label>
										<input type="text"  name="address" class="form-control">
								    </fieldset>
								    <fieldset>
										<label for="email">Email:</label>
										<input type="email"  name="email" class="form-control">
								    </fieldset>
								    <fieldset>
										<label for="last-name">Phone No:</label>
										<input type="number"  name="phone" class="form-control">
								    </fieldset>
								    <fieldset>
								    	<button type="submit" name="submit" id="send-button" class="btn main-btn">Submit</button>
								    </fieldset>
								</form>
							</div> <!-- /.subscribe-form -->
						</div> <!-- /.col-md-4 -->
						<div class="col-md-8">
							<div class="flexslider">
								<ul class="slides">

									 <?php
                                $select=mysqli_query($link,"SELECT * FROM ".$prefix."banner");
                                while($row=mysqli_fetch_object($select)){
                                ?>
									<li>
										<img src="<?=UPLOAD_IMG_PATH.$row->side_img?>" alt="">
										<div class="flex-caption">
											<p><?=$row->title?></p>
										</div>
									</li>

								<?php } ?>
								
								</ul>
							</div> <!-- /.flexslider -->
						</div> <!-- /.col-md-8 -->
					</div> <!-- /.row -->
				</div> <!-- /.slider-wrapper -->
			</div> <!-- /.top-content -->

			<div class="services box-content">
				<div class="row">
					<div class="col-md-offset-2 col-md-8 services-header">
						<h5 class="widget-title"><?=htmlspecialchars_decode(anything('about','title',1));?></h5>
						<span></span>
						<p><?=htmlspecialchars_decode(anything('about','description',1));?></p>
					</div> <!-- /.services-header -->
				</div> <!-- /.row -->
				<div class="row">
					<div class="col-md-4 service-item">
						<div class="service-icon">
							<i class="fa fa-globe"></i>
						</div>
						<div class="service-content">
							<h4 class="service-title"><?=htmlspecialchars_decode(anything('about','hspace1',1));?></h4>
							<p><?=htmlspecialchars_decode(anything('about','description1',1));?></p>
							<!-- <a href="#" class="read-more">Read More &rarr;</a> -->
						</div>
					</div> <!-- /.service-item -->
					<div class="col-md-4 service-item">
						<div class="service-icon">
							<i class="fa fa-tree"></i>
						</div>
						<div class="service-content">
							<h4 class="service-title"><?=htmlspecialchars_decode(anything('about','hspace2',1));?></h4>
							<p><?=htmlspecialchars_decode(anything('about','description2',1));?></p>
							<!-- <a href="#" class="read-more">Read More &rarr;</a> -->
						</div>
					</div> <!-- /.service-item -->
					<div class="col-md-4 service-item">
						<div class="service-icon">
							<i class="fa fa-home"></i>
						</div>
						<div class="service-content">
							<h4 class="service-title"><?=htmlspecialchars_decode(anything('about','hspace3',1));?></h4>
							<p><?=htmlspecialchars_decode(anything('about','description3',1));?></p>
							<!-- <a href="#" class="read-more">Read More &rarr;</a> -->
						</div>
					</div> <!-- /.service-item -->
				</div> <!-- /.row -->
			</div> <!-- /.services -->

			<div class="last-causes box-content">
				<div class="row">
					<div class="col-md-12">
						<h4 class="widget-title"><span>Our Forcast Projects</span></h4>
					</div> <!-- /.col-md-12 -->
				</div> <!-- /.row -->
				<div class="row">

					 <?php
                                $select4=mysqli_query($link,"SELECT * FROM ".$prefix."forcast");
                                while($row4=mysqli_fetch_object($select4)){
                                ?>
					
					<div class="col-md-4 col-sm-6 cause-grid">
						<div class="cause-thumb">
							<img src="<?=UPLOAD_IMG_PATH.$row4->image?>" alt="">
							<div class="cause-hover">
								<div class="cause-holder clearfix">
									<div class="progress">
										<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
									</div>
									<span class="raised pull-left">Budget: ₹<?=$row4->rupees?></span>
									<span class="goal pull-right">Location: <?=$row4->location?></span>
								</div>
							</div>
						</div> <!-- /.cause-thumb -->
						<div class="cause-content">
							<h4 class="cause-title"><a href="cause-detail.html"><?=$row4->title?></a></h4>
							<p><?=htmlspecialchars_decode($row4->content)?></p>
							
						</div> <!-- /.cause-content -->
					</div> <!-- /.col-md-3 -->
					
					<?php } ?>
				</div> <!-- /.row -->
			</div> <!-- /.last-causes -->
			
			<div class="row">
				<div class="col-md-8">
					<div class="box-content">
						<div class="row">
							<div class="col-md-12">
								<h4 class="widget-title"><span>Latest News</span></h4>
							</div>
						</div>
						<div class="row">
							 <?php
                                $select2=mysqli_query($link,"SELECT * FROM ".$prefix."news");
                                while($row2=mysqli_fetch_object($select2)){
                                ?>
							<div class="col-md-6 col-sm-6 post-grid">
								<div class="post-thumb">
									<a href="blog-single.html">
										<img src="<?=UPLOAD_IMG_PATH.$row2->image?>" alt="">
									</a>
								</div> <!-- /.post-thumb -->
								<div class="post-content">
									<p class="post-meta"><a href="#"><?=date("F d, Y",strtotime($row2->date))?></a></p>
									<h3 class="post-title"><a href="blog-single.html"><?=$row2->title?></a></h3>
									<h5><a href="blog-single.html"><?=htmlspecialchars_decode($row2->content)?></a></h5>
									<!-- <a href="blog-single.html" class="read-more">Continue Reading &rarr;</a> -->
								</div> <!-- /.post-content -->
							</div> <!-- /.post-grid -->
						<?php } ?>
							
						</div> <!-- /.row -->
					</div> <!-- /.box-content -->
					<div class="box-content">
						<div class="row">
							<div class="col-md-12">
								<h4 class="widget-title"><span>What Others Said</span></h4>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12 testimonials-wrapper">

							
								<ul class="testi-tabs clearfix">
									<?php 
            $selectgcat=mysqli_query($link, "SELECT * FROM ".$prefix."testimonial");
            while($rowgcat=mysqli_fetch_object($selectgcat))
            { ?>

									<li <?php if($rowgcat->id==2){ ?> class="active" <?php } ?>>
									    <a href="#testi-content-<?=$rowgcat->id?>">
											<img src="<?=UPLOAD_TMB_IMG_PATH.$rowgcat->image?>" alt="">
									    </a>
									</li>
								<?php } ?>	
								</ul>

							

								    <div class="testi-wrapper">

								<?php 
            $selectgcat1=mysqli_query($link, "SELECT * FROM ".$prefix."testimonial");
            while($rowgcat1=mysqli_fetch_object($selectgcat1))
            { ?>
					<div id="testi-content-<?=$rowgcat1->id?>" class="testi-content <?php if($rowgcat1->id==2){?>active <?php }?>">
									    <div class="testi-author">
											<h6><?=$rowgcat1->name?></h6>
									    </div>
									    <p>
									    <?=htmlspecialchars_decode($rowgcat1->msg)?>
									    </p>
									</div>
									<?php } ?>
									</div>

								  <!-- //.testi-wrapper -->
							</div> <!-- /.col-md-12 -->
						</div> <!-- /.row -->
					</div> <!-- /.box-content -->
				</div> <!-- /.col-md-8 -->
				<div class="col-md-4">
					<div class="box-content">
						<h4 class="widget-title"><span>Our Gallery</span></h4>
						<div class="gallery-wrapper">

							 <?php
                                $select1=mysqli_query($link,"SELECT * FROM ".$prefix."gallery");
                                while($row1=mysqli_fetch_object($select1)){
                                ?>
							<div class="gallery-thumb">
								<a href="<?=UPLOAD_IMG_PATH.$row1->image?>" class="fancybox" data-fancybox-group="group3">
									<img src="<?=UPLOAD_IMG_PATH.$row1->image?>" alt="">
								</a>
							</div> <!-- /.gallery-thumb -->
							<?php } ?>
							
						</div> <!-- /.gallery-wrapper -->
					</div> <!-- /.box-content -->
					<div class="box-content">
						<h4 class="widget-title"><span><i class="fa fa-calendar-o" aria-hidden="true"></i> Notice Board</span></h4>
						<div class="events-sidebar">
							<marquee direction="up" onmouseover="this.stop();" onmouseout="this.start();">
							<ul>
								<li class="event-item">
									<?php
                                $select3=mysqli_query($link,"SELECT * FROM ".$prefix."notice");
                                while($row3=mysqli_fetch_object($select3)){
                                ?>
									<div class="event-content">
										<h4 class="event-title"><?=$row3->title?></h4>
										<p class="event-meta"><?=date("F d, Y",strtotime($row3->datetime))?></p>
									</div>
								<?php } ?>
								</li>
								
							</ul>
						</marquee>
							
						</div> <!-- /.events-sidebar -->
					</div> <!-- /.box-content -->
				</div> <!-- /.col-md-4 -->
			</div> <!-- /.row -->

		</div> <!-- /.container -->

		
		<?php include "include/footer.php" ?>

		

    </body>
</html>